# Site settings
title: Lucas' Blog and Website
email: lucas@marcelli.ca
description: "My name is Lucas Marcelli. I like coding, cats and space. This is my website."
baseurl: ""
url: "http://marcelli.ca"
twitter_username: lucasmarcelli
github_username:  lucasm39
facebook_username:  lmarcelli

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]


defaults:
  -
    scope:
      path: "" 
    values:
      author: "Lucas"
      owner: "Lucas Marcelli"
      nav: "no"
      schoolyear: "4th"
      schooltype: "Undergraduate"
      school: "Queen's University"